/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formsTuristickaAgencija;

import controller.KlijentskiKontroler;
import domain.TAVU;
import domain.TuristickaAgencija;
import domain.VrstaUsluge;
import java.awt.Cursor;
import java.awt.Window;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.TableModelVrstaUslugeTuristickaAgencija;

/**
 *
 * @author Lenovo
 */
public class FormaTuristickaAgencija extends javax.swing.JDialog {
    TuristickaAgencija pomocna=null;
    /**
     * Creates new form FormaTuristickaAgencija
     */
    public FormaTuristickaAgencija(Window parent, boolean modal, TuristickaAgencija ta, int signal) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        initComponents();
        setLocationRelativeTo(null);
        pomocna=ta;
        switch (signal){
            case 1:
                setTitle("Detalji agencije");
                jTextFieldNaziv.setEditable(false);
                jTextFieldAdresa.setEditable(false);
                jTextFieldUsername.setEditable(false);
                jPasswordFieldSifra.setEnabled(false);
                jTextFieldNaziv.setText(pomocna.getNaziv());
                jTextFieldAdresa.setText(pomocna.getAdresa());
                jTextFieldUsername.setText(pomocna.getUsername());
                jPasswordFieldSifra.setText(pomocna.getPassword());
                jButtonIzmeni.setEnabled(false);
                jButtonDodaj.setEnabled(false);
                jButtonObrisi.setEnabled(false);
                jComboBoxVrstaUsluge.setEnabled(false);
                break;
            case 2:
                setTitle("Izmena agencije");
                jTextFieldNaziv.setEditable(false);
                jTextFieldAdresa.setEditable(true);
                jTextFieldUsername.setEditable(false);
                jPasswordFieldSifra.setEditable(false);
                jTextFieldNaziv.setText(pomocna.getNaziv());
                jTextFieldAdresa.setText(pomocna.getAdresa());
                jTextFieldUsername.setText(pomocna.getUsername());
                jPasswordFieldSifra.setText(pomocna.getPassword());
                jButtonIzmeni.setEnabled(true);
                jButtonDodaj.setEnabled(true);
                jButtonObrisi.setEnabled(true);
                jComboBoxVrstaUsluge.setEnabled(true);
                break;
        }
        TableModelVrstaUslugeTuristickaAgencija model = new TableModelVrstaUslugeTuristickaAgencija();
        Thread th = new Thread(model);
        th.start();
        jTableVrstaUsluge.setModel(model);
        model.setParametar(pomocna.getIdAgencije());
        this.popuniVrsteUsluge();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNaziv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldAdresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordFieldSifra = new javax.swing.JPasswordField();
        jLabelPromeniSifru = new javax.swing.JLabel();
        jButtonOtkazi = new javax.swing.JButton();
        jButtonIzmeni = new javax.swing.JButton();
        jCheckBoxPrikaziSifru = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVrstaUsluge = new javax.swing.JTable();
        jButtonObrisi = new javax.swing.JButton();
        jButtonDodaj = new javax.swing.JButton();
        jComboBoxVrstaUsluge = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Naziv agencije");

        jLabel2.setText("Adresa");

        jLabel3.setText("Username");

        jLabel4.setText("Sifra");

        jLabelPromeniSifru.setText("Promeni sifru");
        jLabelPromeniSifru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPromeniSifruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelPromeniSifruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelPromeniSifruMouseExited(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jButtonIzmeni.setText("Izmeni");
        jButtonIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniActionPerformed(evt);
            }
        });

        jCheckBoxPrikaziSifru.setText("Prikazi sifru");
        jCheckBoxPrikaziSifru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxPrikaziSifruActionPerformed(evt);
            }
        });

        jLabel5.setText("Vrste usluge");

        jTableVrstaUsluge.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableVrstaUsluge);

        jButtonObrisi.setText("Obrisi");
        jButtonObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiActionPerformed(evt);
            }
        });

        jButtonDodaj.setText("Dodaj");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jButtonOtkazi))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jButtonIzmeni))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonObrisi))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAdresa)
                            .addComponent(jTextFieldUsername)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxPrikaziSifru, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPromeniSifru))
                            .addComponent(jPasswordFieldSifra)
                            .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxVrstaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordFieldSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPromeniSifru)
                    .addComponent(jCheckBoxPrikaziSifru))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButtonObrisi)
                    .addComponent(jButtonDodaj)
                    .addComponent(jComboBoxVrstaUsluge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOtkazi)
                    .addComponent(jButtonIzmeni)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelPromeniSifruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPromeniSifruMouseEntered
        jLabelPromeniSifru.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelPromeniSifruMouseEntered

    private void jLabelPromeniSifruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPromeniSifruMouseExited
        jLabelPromeniSifru.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelPromeniSifruMouseExited

    private void jLabelPromeniSifruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPromeniSifruMouseClicked
        new FormaTuristickaAgencijaPromenaSifre(this, true, pomocna).setVisible(true);
    }//GEN-LAST:event_jLabelPromeniSifruMouseClicked

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jCheckBoxPrikaziSifruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxPrikaziSifruActionPerformed
        if(jCheckBoxPrikaziSifru.isSelected()){
            jPasswordFieldSifra.setEchoChar((char) 0);
        }else{
            jPasswordFieldSifra.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxPrikaziSifruActionPerformed

    private void jButtonIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniActionPerformed
        try {
            if(jTextFieldAdresa.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Greska!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String adresa = jTextFieldAdresa.getText();
            
            if(adresa.length()>100){
                JOptionPane.showMessageDialog(this, "Adresa mora imati manje od 50 karaktera!", "Greska!", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            TuristickaAgencija ta = new TuristickaAgencija(pomocna.getIdAgencije(), pomocna.getNaziv(), adresa, pomocna.getUsername(), pomocna.getPassword());
            KlijentskiKontroler.getInstance().updateTuristickaAgencija(ta);
            JOptionPane.showMessageDialog(this, "Uspesno izmenjena turisticka agencija.", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(FormaTuristickaAgencija.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIzmeniActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
        try {
            VrstaUsluge vu = (VrstaUsluge) jComboBoxVrstaUsluge.getSelectedItem();
            TAVU t = new TAVU(null, pomocna, vu);
            
            KlijentskiKontroler.getInstance().addTAVU(t);
            JOptionPane.showMessageDialog(this, "Uspesno dodata vrsta usluge.", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            this.refreshTable();
        } catch (Exception ex) {
            Logger.getLogger(FormaTuristickaAgencija.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void jButtonObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiActionPerformed
        int row = jTableVrstaUsluge.getSelectedRow();
        
        if(row>=0){
            VrstaUsluge vu = ((TableModelVrstaUslugeTuristickaAgencija) jTableVrstaUsluge.getModel()).getSelectedVrstaUsluge(row);
            TAVU t = new TAVU(null, pomocna, vu);
            int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                    + "obrisete ovu vrstu usluge? " + vu.toString(), "Konfirmacija", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.NO_OPTION) {
                return;
            }

            if (result == JOptionPane.YES_OPTION) {
                try {
                    KlijentskiKontroler.getInstance().deleteTAVU(t);
                    this.refreshTable();
                    JOptionPane.showMessageDialog(this, "Uspesno obrisana vrsta usluge.");
                } catch (Exception ex) {
                    Logger.getLogger(FormaTuristickaAgencija.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex.toString(), "Greska!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "Morate odabrati nacionalnost!", "Obavestenje!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonIzmeni;
    private javax.swing.JButton jButtonObrisi;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JCheckBox jCheckBoxPrikaziSifru;
    private javax.swing.JComboBox jComboBoxVrstaUsluge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPromeniSifru;
    private javax.swing.JPasswordField jPasswordFieldSifra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVrstaUsluge;
    private javax.swing.JTextField jTextFieldAdresa;
    private javax.swing.JTextField jTextFieldNaziv;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
    private void popuniVrsteUsluge() {
    try {
        ArrayList<VrstaUsluge> vrste = KlijentskiKontroler.getInstance().getAllVrstaUsluge();
        Set<String> naziviUsluga = new HashSet<>();

        jComboBoxVrstaUsluge.removeAllItems();

        for (VrstaUsluge u : vrste) {
            if (!naziviUsluga.contains(u.getNazivUsluge())) { 
                naziviUsluga.add(u.getNazivUsluge());
                jComboBoxVrstaUsluge.addItem(u);
            }
        }
    } catch (Exception ex) {
        Logger.getLogger(FormaPretraziTuristickaAgencija.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    void refreshTable(){
        TableModelVrstaUslugeTuristickaAgencija tm = (TableModelVrstaUslugeTuristickaAgencija) jTableVrstaUsluge.getModel();
        tm.refreshTable();
    }
}
